modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Crimix/KnowledgeDrop/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]]
modId="knowledgedrop"
version="${version}"
displayName="Knowledge Drop"
updateJSONURL="${update_url}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/knowledge-drop"
logoFile="knowledgedrop-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''Make mobs drop their knowledge as enchantment books'''

[[dependencies.knowledgedrop]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.knowledgedrop]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.knowledgedrop]]
    modId="blackdogsmoddinglibrary"
    mandatory=true
    versionRange="${bml_version_range}"
    ordering="BEFORE"
    side="BOTH"
